// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBURdWFRZPqGvXW_D3T8XJih5LqokQMruw',
    appId: '1:82994678210:android:59cc5d015e4a25cd6aae5b',
    messagingSenderId: '82994678210',
    projectId: 'pipek-7244e',
    storageBucket: 'pipek-7244e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlF1mO2Q27HxlsB8dNhs1Nh1c1tYx8-Iw',
    appId: '1:82994678210:ios:133abfab315061a86aae5b',
    messagingSenderId: '82994678210',
    projectId: 'pipek-7244e',
    storageBucket: 'pipek-7244e.firebasestorage.app',
    iosBundleId: 'com.example.alBarq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlF1mO2Q27HxlsB8dNhs1Nh1c1tYx8-Iw',
    appId: '1:82994678210:ios:133abfab315061a86aae5b',
    messagingSenderId: '82994678210',
    projectId: 'pipek-7244e',
    storageBucket: 'pipek-7244e.firebasestorage.app',
    iosBundleId: 'com.example.alBarq',
  );
}
